### PR TITLE
Fix #580: use source link to enrich pdbs with github information

### LINKED ISSUE #580: Use SourceLink to improve debugging experience
[SourceLink](https://github.com/ctaggart/SourceLink) will boost up the debugging experience when you debug weavers.

### PR DESCRIPTION
**Pull request by tom-englert**

### CODE REVIEW

**Comment by ltrzesniewski** [comment]
Why don't you use `Microsoft.SourceLink.GitHub` instead? It supersedes `SourceLink.Create.CommandLine`.

Also, you may want to add these:

```xml
<PublishRepositoryUrl>true</PublishRepositoryUrl>
<DebugType>embedded</DebugType>
<Deterministic>true</Deterministic>
<DeterministicSourcePaths>true</DeterministicSourcePaths>
```

I've seen better results with embedded PDBs with this package. Sometimes VS wouldn't load external ones.

**Comment by tom-englert** [comment]
@ltrzesniewski `Microsoft.SourceLink.GitHub` it is still beta, and the results of `SourceLink.Create.CommandLine` were all OK for me up to now.
However we can try the Microsoft version - maybe you can provide an alternate PR?

**Comment by ltrzesniewski** [comment]
I've used the Microsoft one on several projects without issue and the one you used encourages you to use the Microsoft one in its readme (read the ".NET Foundation" paragraph [here](https://github.com/ctaggart/SourceLink#net-foundation)). I don't know why they're in beta for so long - it works fine.

I don't really see the point in doing an alternate PR for this, it's a one-line change (except if you decide to use the additional properties, which would make it a 5-line change 😉).

**Comment by tom-englert** [comment]
replaced by #584

**Pull request closed without merging**
