### PR TITLE
README.md: move an element out of addins list

### PR DESCRIPTION
**Pull request by knocte**
Realm is not an addin, I suppose it's a project that uses Fody.

### CODE REVIEW

**Comment by SimonCropp** [comment]
Isnt this a weaver? https://github.com/realm/realm-dotnet/tree/master/Weaver/RealmWeaver.Fody

**Comment by knocte** [comment]
Ah cool, I'll correct the link then.

**Comment by knocte** [comment]
@SimonCropp fixed

**Comment by SimonCropp** [comment]
Thanks

**Pull request merged**
