### PR TITLE
Fix package finder for linux. (Fixes #477)

### LINKED ISSUE #477: Fody: An unhandled exception occurred- in InternalGetAssemblyName
My solution builds fine on both Windows and Mac. When building in Ubuntu 16.04.3 LTS, it fails:

```

Target FodyTarget:
      Fody: Fody (version 1.0.0.0) Executing
      Fody: ProjectDirectory: '/home/tshabtay/Personal/git/MonoAGS/Source/Engine/AGS.Engine/'.
      Fody: AssemblyPath: '/home/tshabtay/Personal/git/MonoAGS/Source/Engine/AGS.Engine/obj/Debug/AGS.Engine.dll'
      Fody: Found path to weavers file '/home/tshabtay/Personal/git/MonoAGS/Source/Engine/AGS.Engine/FodyWeavers.xml'.
      Fody: SolutionDirectory path is '/home/tshabtay/Personal/git/MonoAGS/'
      Fody: Finding weavers
      Fody: FindAddinDirectories:
      Fody:   No PackageDefinitions
      Fody:   Skipped SolutionDir/Packages convention '/home/tshabtay/Personal/git/MonoAGS/Packages' since it doesn't exist.
      Fody:   Skipped directory from Nuget Config since it could not be derived.
      Fody:   Scanning the MsBuildThisFileDirectory parent: /home/tshabtay/.nuget/packages/'.
      Fody:     Fody weaver file added '/home/tshabtay/.nuget/packages/propertychanged.fody/2.1.4/propertychanged.fody.dll'
      Fody:     Fody weaver file added '/home/tshabtay/.nuget/packages/propertychanged.fody/2.2.5/netclassicweaver/propertychanged.fody.dll'
      Fody:   Skipped scanning '/home/tshabtay/Personal/git/MonoAGS/Tools' since it doesn't exist.
      Fody:   Scanning NuGetPackageRoot '/home/tshabtay/.nuget/packages/'.
      Fody:     Fody weaver file added '/home/tshabtay/.nuget/packages/propertychanged.fody/2.1.4/propertychanged.fody.dll'
      Fody:     Fody weaver file added '/home/tshabtay/.nuget/packages/propertychanged.fody/2.2.5/netclassicweaver/propertychanged.fody.dll'
      Fody: No Weaver project file found.
    MSBUILD : error : Fody: An unhandled exception occurred:
    MSBUILD : error : Exception:
    MSBUILD : error : 
    MSBUILD : error : StackTrace:
    MSBUILD : error :   at (wrapper managed-to-native) System.Reflection.Assembly:InternalGetAssemblyName (string,Mono.MonoAssemblyName&,string&)
    MSBUILD : error :   at System.Reflection.AssemblyName.GetAssemblyName (System.String assemblyFile) [0x00014] in /run/build/mono/mcs/class/corlib/System.Reflection/AssemblyName.cs:421 
    MSBUILD : error :   at AssemblyVersionReader.GetAssemblyVersion (System.String path) [0x00000] in C:\projects\fody\Fody\AssemblyVersionReader.cs:11 
    MSBUILD : error :   at System.Linq.CachingComparer`2[TElement,TKey].SetElement (TElement element) [0x00000] in /run/build/mono/external/corefx/src/System.Linq/src/System/Linq/OrderedEnumerable.cs:484 
    MSBUILD : error :   at System.Linq.OrderedEnumerable`1[TElement].TryGetFirst (System.Boolean& found) [0x00031] in /run/build/mono/external/corefx/src/System.Linq/src/System/Linq/OrderedEnumerable.cs:258 
    MSBUILD : error :   at System.Linq.Enumerable.TryGetFirst[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Boolean& found) [0x00018] in /run/build/mono/external/corefx/src/System.Linq/src/System/Linq/First.cs:59 
    MSBUILD : error :   at System.Linq.Enumerable.FirstOrDefault[TSource] (System.Collections.Generic.IEnumerable`1[T] source) [0x00000] in /run/build/mono/external/corefx/src/System.Linq/src/System/Linq/First.cs:40 
    MSBUILD : error :   at AddinFinder.FindAddinAssembly (System.String packageName) [0x00017] in C:\projects\fody\Fody\AddinFinder\AddinFilesEnumerator.cs:13 
    MSBUILD : error :   at Processor.FindAssemblyPath (System.String weaverName) [0x00000] in C:\projects\fody\Fody\WeaverAssemblyPathFinder.cs:6 
    MSBUILD : error :   at Processor.ProcessConfig (WeaverEntry weaverConfig) [0x00027] in C:\projects\fody\Fody\InstanceLinker\WeaversConfiguredInstanceLinker.cs:24 
    MSBUILD : error :   at Processor.ConfigureWhenWeaversFound () [0x00016] in C:\projects\fody\Fody\InstanceLinker\WeaversConfiguredInstanceLinker.cs:9 
    MSBUILD : error :   at Processor.FindWeavers () [0x00062] in C:\projects\fody\Fody\Processor.cs:117 
    MSBUILD : error :   at Processor.Inner () [0x00087] in C:\projects\fody\Fody\Processor.cs:88 
    MSBUILD : error :   at Processor.Execute () [0x00034] in C:\projects\fody\Fody\Processor.cs:49 
    MSBUILD : error : 
      Fody:   Finished Fody 11ms.
Done building target "FodyTarget" in project "AGS.Engine.csproj" -- FAILED.

Done building project "AGS.Engine.csproj" -- FAILED.

Build FAILED.

```

Tested with Fody 2.3.22, building from MonoDevelop 7.1 build 1291, using Mono 4.2.1 (Debian 4.2.1.102+dfsg2-7ubuntu4).

To reproduce, build my solution which can be found here: https://github.com/tzachshabtay/MonoAGS

Side note: your exception friendly printer (https://github.com/Fody/Fody/blob/3b238d48d9671a10352fbd42ec67d90c7597ebc8/FodyCommon/ExceptionExtensions.cs) does not print the type of the exception, which would be helpful here as it seems that the exception has en empty message.

### PR DESCRIPTION
**Pull request by SebastianStehle**
Fixes #477

### CODE REVIEW

**Comment by SimonCropp** [comment]
Kool. Can u also add a unit test so it doesn’t regress in the future

**Comment by SebastianStehle** [comment]
If I would see an easy way how. There are only integration tests and I think I have to extract the file access layer to mock it and simulate the windows and linux behavior.

**Comment by SimonCropp** [comment]
Ok forget the test. I will look into running all tests on linux. Does your change pass all other tests?

**Comment by SebastianStehle** [comment]
On my machine yes, don't know why AppVeyor complains.

**Pull request merged**
