### PR TITLE
Support for verifiers (currently PEVerify)

### PR DESCRIPTION
**Pull request by GeertvanHorrik**

### CODE REVIEW

**Comment by GeertvanHorrik** [comment]
Copying all refs works. I know it's not the best solution, but it works...

**Comment by SimonCropp** [comment]
yeah but i am concerned about unintended side effects of other tools that make assumptions about the state of the obj directory

**Comment by GeertvanHorrik** [comment]
I understand, just making babysteps to check where we can improve.

**Comment by SimonCropp** [comment]
so there is not a safe subset of known error codes about missing refs we can pass into the `/ignore` param of peverfiy?

If not i think we should go with copy the files to a staging dir for verification, or plug into the after build. Thoughts?

**Comment by GeertvanHorrik** [comment]
Yes, about missing refs there is. But there are more. For example:

```
*.Controls.AdvertisementControl::.cctor][offset 0x0000000A] Unable to resolve token.
```

You don't want to miss these. In this case it's a WIN 8.1 project with shared projects (shouldn't make a difference though). When I copy references, all works.

**Comment by SimonCropp** [comment]
`Unable to resolve token` ok agreed that could be a valid error

**Comment by GeertvanHorrik** [comment]
1>      Verifying assembly
1>      Finished verification in 525ms.

Not bad for an assembly with 700 types and 70 references (don't ask, it now copies all System.* assemblies as well).

**Comment by SimonCropp** [comment]
add a new verification task and add it to the afterbuild similar to what is done here https://github.com/Fody/Fody/blob/master/NuGet/Fody.targets#L45

**Comment by GeertvanHorrik** [comment]
ok, will work on that, thanks for the hints.

**Comment by SimonCropp** [comment]
no worries. the code should be pretty simple in the end. 

* task takes in the `$(TargetPath)` in msbuild
* resolves peverify
* log errors

Since u dont need to worry about appdomain juggling like it need to do for the weavers

**Comment by SimonCropp** [comment]
well also do config switching :)

**Comment by GeertvanHorrik** [comment]
Introducing Configuration class so we can share configuration over multiple tasks.

**Comment by GeertvanHorrik** [comment]
Also need to add FinalAssemblyFileName to support the final output path.

**Comment by GeertvanHorrik** [comment]
1>      Verifying assembly
1>      Finished verification in 459ms.

woohoo! :-)

**Comment by GeertvanHorrik** [comment]
btw. I prepared the Configuration object so it accepts DefinedConstants. Then we can customize the configuration based on both xml **and** constants in a single place for both tasks.

**Comment by GeertvanHorrik** [comment]
Did you find time to review it?

**Comment by SimonCropp** [comment]
will try to get to it over the weekend

**Comment by SimonCropp** [comment]
manually merged this and deplyed a beta.

I called yagni on multiple verifiers. when we think of a second one we can plug that in

**Comment by GeertvanHorrik** [comment]
1>      Verifying assembly
1>      Finished verification in 335ms.

Works great :-)

**Comment by SimonCropp** [comment]
I will test more and move it out of beta today

**Pull request closed without merging**
